[package]
name = "display_json"
version = "0.1.0"
authors = ["jofas <jonas@fc-web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
display_json_derive = { path = "display_json_derive" }
serde = { version = "^1.0.125", features = ["derive"] }
serde_json = "^1.0.64"
